In [26]:
import numpy as np
# 1 dimensional array
data_1 = [809, 731, 588, 18, 200, 70, 45]
arr_1 = np.array(data_1)
print(arr_1)
arr_1.dtype

[809 731 588  18 200  70  45]


dtype('int32')

In [27]:
#list of lists
data_2 = [range(1, 5), range(5, 9)]
arr_2 = np.array(data_2) # 2 dimensional array
print(arr_2)
arr_2.dtype

# to convert array back to list  
arr_2.tolist()

[[1 2 3 4]
 [5 6 7 8]]


[[1, 2, 3, 4], [5, 6, 7, 8]]

In [7]:
np.zeros(10)
# Returns a new array of given shape and type, filled with zeros.


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [166]:
arr_3 = np.zeros((3,6))
print(arr_3)
print(arr_3.ndim)
print(arr_3.shape)
print(arr_3.size)  # total number of elements
len(arr_3)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
2
(3, 6)
18


3

In [13]:
np.ones(10)
# # Returns a new array of given shape and type, setting values to 1.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.linspace(0,1,5)

## numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# Return evenly spaced numbers over a specified interval.
#Returns num evenly spaced samples, calculated over the interval [start, stop].
# The endpoint of the interval can optionally be excluded.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# Return numbers spaced evenly on a log scale.
np.logspace(0,3,4)
# 10**0 to 10**3 with 4 number of samples

array([   1.,   10.,  100., 1000.])

In [165]:
array3 = np.arange(5)
#print(array3)
array4 = array3.astype(float) # to change the type of the array
print(array4)
print(array4.dtype) # float64
print(array4.ndim)
print(array4.shape)
array4.size
print(len(array4))

[0. 1. 2. 3. 4.]
float64
1
(5,)
5


4.3- Reshaping

In [77]:
arr_5 = np.arange(20, dtype=float).reshape(2,10)
print(arr_5)
arr_5.reshape(5,4)


[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

Add an axis

In [70]:
x = np.array([0,1,2,3])
print(x)
#x_col = x[:, np.newaxis]
x_col = x[:, None]
print(x_col)
print(x_col.T) # for one dimensional array it has no affect

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3]]


In [89]:
ls_1 = [[5,8,9],[6,5,14],[23,12,7]]
ar_1 = np.array(ls_1)
print(ar_1.ndim)
print(ar_1)
#print(ar_1.T)
ar_flat = ar_1.flatten() # will return a flat array
print(ar_flat)
ar_flat[0] = 33 # to change the value at index
print(ar_flat)

2
[[ 5  8  9]
 [ 6  5 14]
 [23 12  7]]
[ 5  8  9  6  5 14 23 12  7]
[33  8  9  6  5 14 23 12  7]


In [95]:
##Stack arrays

arr = np.array([2,3])
arr_1 = np.array([4,5])

#arr_2 = np.stack((arr, arr_1))

arr_2 = np.stack((arr, arr_1)).T
print(arr_2)

[[2 4]
 [3 5]]


In [167]:
# selection

array = np.arange(16, dtype= float).reshape(4,4)
print(array)
print(array[0,::-1])

array[0, 2]  # slices like a list

array[:, 2] # returns 1 dimensional array of column 2
array[1,:] # returns 1d array of row 1
array[:, 1:] # prints out all rows starting from column 1
array[:, 1:3]
array[:, [0,1,2,3]]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[3. 2. 1. 0.]


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [113]:
array = np.arange(16, dtype= float).reshape(4,4)
print(array)
array2 = array[array>5]
print(array2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [164]:
# Vectorized operation

nums = np.arange(8)
print(nums)
nums2 = np.array([1,-2,-3,4,-5,6,-7,16])
print(nums + np.arange(8)) # adds array elemnt wise
print(print(nums*10)) 
print(np.sqrt(nums))
#np.ceil(nums) # rounds the nearest integer

# np.maximum(nums, np.array([1,-2,-3,4,-5,6,-7,17]))
print(np.maximum(nums, nums2))

[0 1 2 3 4 5 6 7]
[ 0  2  4  6  8 10 12 14]
[ 0 10 20 30 40 50 60 70]
None
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131]
[ 1  1  2  4  4  6  6 16]


In [130]:
# compute euclidean distance between two vectors

# euclidean distance : The distance between two vectors is defined as the square root of the sum of the squares of the 
# differences between the corresponding coordinates of the vector

vec1 = np.random.randn(10)
vec2= np.random.randn(10)

distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
print(distance)

6.478524985105116


In [163]:
rnd = np.random.randn(8, 4)
print(rnd)

print(rnd.std()) # measures the spread of the array
print(rnd.argmin()) # gives the index of minimum element of array
print(rnd.argmax()) # gives index of maximum value
print(rnd.sum(axis=0)) # will give a array containg sum of all the columns
print(rnd.sum(axis=1)) # gives the sum of rows
print((rnd > 0).sum()) # returns number of positive values
print((rnd> 0).any()) # check if any value is true
print((rnd> 0).all()) # check if all the values are true
print(np.random.seed(12234)) # will set the seed


[[-0.53481712  0.18558172  0.38014325  1.18388892]
 [-1.47121459 -1.11701449 -2.13818035 -1.07230259]
 [ 0.82449002  0.55090109 -1.32740791  0.34634166]
 [-0.04898868 -0.7457014   0.55881044  0.80033756]
 [-1.44891463 -0.1349495  -0.21602693  0.60164279]
 [-0.04178484 -0.23766393  1.25964033  1.15320544]
 [-0.04862288 -0.34317779  0.35593984 -0.66206705]
 [-0.16498907  0.09214453  0.05056265 -0.05840095]]
0.8144939726520622
6
22
[-2.93484178 -1.74987976 -1.07651868  2.29264579]
[ 1.21479678 -5.79871202  0.39432485  0.56445793 -1.19824826  2.133397
 -0.69792788 -0.08068283]
14
True
False
None


In [144]:
np.random.seed(12234) 

In [150]:
array= np.array([[ 0, 0, 0],
                 [10,10,10],
                 [20,20,20],
                 [30,30,30]])

array2 = np.array([5,6,7])

print(array + array2)
            

[[ 5  6  7]
 [15 16 17]
 [25 26 27]
 [35 36 37]]


In [151]:
array= np.array([[ 0],
                 [10],
                 [20],
                 [30]])

array2 = np.array([5,6,7])

print(array + array2)

[[ 5  6  7]
 [15 16 17]
 [25 26 27]
 [35 36 37]]


4.8 : Exercise

In [162]:
array8 = np.random.randn(4,2)
print(array8)

# for each column find the row index of the minimum value

print(array8[:,0].argmin())  # prints out the row index of the minimum value in column 1
print(array8[:,1].argmin())

[[-1.13523365 -1.13225996]
 [-0.72489198 -0.22903211]
 [ 0.89721425  0.70105278]
 [-0.1578779  -0.49929006]]
0
0


In [1]:
array8 = np.random.randn(4,2)

print(array8)

def standarize(x):
  
  x_std = x - np.mean(x, axis=0)/np.std(x, axis = 0)  # subtract the mean of the column and divide by 
                                                       # standard division
  return x_std

print(standarize(array8))



[[-0.72685774  2.41718139]
 [-0.97392167 -1.06723647]
 [-0.33623828 -1.28766284]
 [ 0.80515691  1.87025781]]
[[-0.27509103  2.12850484]
 [-0.52215496 -1.35591302]
 [ 0.11552844 -1.57633938]
 [ 1.25692362  1.58158127]]
